### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by yukibtc**
* Replace `nostr-sdk` with `nostr` (`nostr-sdk` contains unnecessary code for this library)
* Remove unnecessary dependencies
* General cleanup

### CODE REVIEW

**Review by grunch — APPROVED** [review]
LGTM! thanks

**Comment by schlunsen** [comment]
Thanks @yukibtc! Learned a thing or two by reading the changes

**Comment by grunch** [comment]
yeah same to me, learned a lot with those changes, thanks again

**Comment by yukibtc** [comment]
Glad I was helpful :)

**Pull request merged**
