### PR TITLE
[Enhancement] Search for multiple vanity `npub` targets

### PR DESCRIPTION
**Pull request by kdmukai**
Example usage:
```
$ cargo run --release -- --vanity-n=rana,h0dl,n0strfan
```

Rationale in the updated README:

> Specifying multiple `vanity-n` targets allows you to leverage the work you've already done to generate each new `npub` candidate. Searching a candidate `npub` for additional targets is incredibly fast because it's just a trivial string compare.
>
> Statistically speaking, searching for `rana,h0dl` should take half the time that searching for `rana` and then doing a second, separate search for `hodl` would take.

### Slightly enhanced console output
When doing a `vanity-n` search, the vanity target itself will be listed in the output. This makes it easier to see which target was found. Especially useful if a long list of target `vanity-n` are specified.

```
==============================================
Vanity npub found:         h0dl
Found matching public key: bbdbfc0412e0ff99bd51bdba4ff732bf3d5d0b3d3be188c970fba3351eb0e41e
Nostr private key:         fab16d1784115fe25cfa4e9e3937e1b506359326af4e6869beadf33f4b9f8484
Nostr public key (npub):   npub1h0dlcpqjurlen023hkaylaejhu746zea80sc3jtslw3n284sus0quhrkwd
Nostr private key (nsec):  nsec1l2ck69uyz907yh86f60rjdlpk5rrtyex4a8xs6d74hen7julsjzqj09dw5
1143455 iterations (about 1x10^6 hashes) in 6 seconds. Avg rate 190575 hashes/second
==============================================
Vanity npub found:         sat0
Found matching public key: 8756f8e3df4fc82d935c89872be2aa8d52afe3e9c40d0a4a5047f57f0ab4fdf2
Nostr private key:         09b0157b6cafa9912e3b19500b6ceef4c7bb00de4eff11a026e5b4e213596b15
Nostr public key (npub):   npub1sat03c7lflyzmy6u3xrjhc4234f2lclfcsxs5jjsgl6h7z45lheqyem0g2
Nostr private key (nsec):  nsec1pxcp27mv475ezt3mr9gqkm8w7nrmkqx7fml3rgpxuk6wyy6edv2szyttv3
1581627 iterations (about 1x10^6 hashes) in 9 seconds. Avg rate 175736 hashes/second
==============================================
Vanity npub found:         h0dl
Found matching public key: bbdbfa8848ebfdfc17bc5d47becb6b3e0d2e6e8bea0ffca42a08c56d004de443
Nostr private key:         19133ed50184450037c0881341d685273ae93896e92b11c8f746aa9045052d4c
Nostr public key (npub):   npub1h0dl4zzga07lc9aut4rmajmt8cxjum5tag8lefp2przk6qzdu3psfmmhvm
Nostr private key (nsec):  nsec1ryfna4gps3zsqd7q3qf5r459yuawjwykay43rj8hg64fq3g994xqagdgyk
1770852 iterations (about 1x10^6 hashes) in 10 seconds. Avg rate 177085 hashes/second
```

### Caveat
This is literally the first Rust code I've ever attempted to work with. My efforts here were basically guess-and-check the whole way.

### CODE REVIEW

**Comment by grunch** [comment]
Thank you for this great contribution 😃 

I tested it and I found something that broke

Rana v0.3.1
Captura desde 2023-01-06 10-15-12

This PR:
Captura desde 2023-01-06 10-15-28

**Comment by kdmukai** [comment]
@grunch, I'll take a look!

If I knew more about Rust, I'd help build out the test suite, but we're right at the limit of my noob abilities right now.

**Comment by grunch** [comment]
tACK

It works like a charm 🥳

**Comment by sha2fiddy** [comment]
this is awesome.  any upper limit to the N npubs?  I was working on my own [Python version](https://github.com/sha2fiddy/nostr-fun) before I discovered this tool, I'm sure this is much more optimized!

**Comment by kdmukai** [comment]
> this is awesome. any upper limit to the N npubs?

No limit on `-n` search targets, but it would be interesting to get some benchmarking to see what performance impact they have as the number increases. If 50 or 100 is not really much different than, say, 2-5, then load up!

> I was working on my own [Python version](https://github.com/sha2fiddy/nostr-fun) before I discovered this tool, I'm sure this is much more optimized!

Same! My python version had trash performance compared to `rana`!!!

**Pull request merged**
